//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/DataService/Service1", ConfigurationName="RemoteService.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/SetDataBase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetDataBaseAsync(string strDatabase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/SetCommString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> SetCommStringAsync(string strCommString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/TestString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestStringAsync(string S);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/GetLoginInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RemoteService.LoginInfo> GetLoginInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/GetSystemParame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RemoteService.ArrayOfXElement> GetSystemParameAsync(string strType, string strModuleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/ExecuteNonQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ExecuteNonQueryAsync(string strSQLCommand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/ExecuteScalar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ExecuteScalarAsync(string strSQLCommand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/UpdateDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> UpdateDataTableAsync(RemoteService.ArrayOfXElement dsChangeDataSet, string strTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/GetSelectRuselt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RemoteService.ArrayOfXElement> GetSelectRuseltAsync(string strSelectCommand);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/GetSelectResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RemoteService.GetSelectResultResponse> GetSelectResultAsync(RemoteService.GetSelectResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/GetSystemParameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RemoteService.ArrayOfXElement> GetSystemParameterAsync(string strType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/GetDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/CommSecurityString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CommSecurityStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Service1/ChangePassWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ChangePassWordAsync(string sServer, string sDomain, string sUser, string sOldPass, string sNewPass);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DataService/Service1")]
    public partial class LoginInfo
    {
        
        private string loginNameField;
        
        private string fullNameField;
        
        private string functionGroupField;
        
        private string departmentField;
        
        private string jobTitleField;
        
        private string accountField;
        
        private string countryField;
        
        private string workShopField;
        
        private string teamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LoginName
        {
            get
            {
                return this.loginNameField;
            }
            set
            {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FunctionGroup
        {
            get
            {
                return this.functionGroupField;
            }
            set
            {
                this.functionGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string JobTitle
        {
            get
            {
                return this.jobTitleField;
            }
            set
            {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WorkShop
        {
            get
            {
                return this.workShopField;
            }
            set
            {
                this.workShopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Team
        {
            get
            {
                return this.teamField;
            }
            set
            {
                this.teamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectResult", WrapperNamespace="http://tempuri.org/DataService/Service1", IsWrapped=true)]
    public partial class GetSelectResultRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DataService/Service1", Order=0)]
        public string strSelectCommand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DataService/Service1", Order=1)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DataService/Service1", Order=2)]
        public int RunType;
        
        public GetSelectResultRequest()
        {
        }
        
        public GetSelectResultRequest(string strSelectCommand, string Message, int RunType)
        {
            this.strSelectCommand = strSelectCommand;
            this.Message = Message;
            this.RunType = RunType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectResultResponse", WrapperNamespace="http://tempuri.org/DataService/Service1", IsWrapped=true)]
    public partial class GetSelectResultResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DataService/Service1", Order=0)]
        public RemoteService.ArrayOfXElement GetSelectResultResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DataService/Service1", Order=1)]
        public string Message;
        
        public GetSelectResultResponse()
        {
        }
        
        public GetSelectResultResponse(RemoteService.ArrayOfXElement GetSelectResultResult, string Message)
        {
            this.GetSelectResultResult = GetSelectResultResult;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface Service1SoapChannel : RemoteService.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<RemoteService.Service1Soap>, RemoteService.Service1Soap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task SetDataBaseAsync(string strDatabase)
        {
            return base.Channel.SetDataBaseAsync(strDatabase);
        }
        
        public System.Threading.Tasks.Task<bool> SetCommStringAsync(string strCommString)
        {
            return base.Channel.SetCommStringAsync(strCommString);
        }
        
        public System.Threading.Tasks.Task<string> TestStringAsync(string S)
        {
            return base.Channel.TestStringAsync(S);
        }
        
        public System.Threading.Tasks.Task<RemoteService.LoginInfo> GetLoginInfoAsync()
        {
            return base.Channel.GetLoginInfoAsync();
        }
        
        public System.Threading.Tasks.Task<RemoteService.ArrayOfXElement> GetSystemParameAsync(string strType, string strModuleName)
        {
            return base.Channel.GetSystemParameAsync(strType, strModuleName);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteNonQueryAsync(string strSQLCommand)
        {
            return base.Channel.ExecuteNonQueryAsync(strSQLCommand);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteScalarAsync(string strSQLCommand)
        {
            return base.Channel.ExecuteScalarAsync(strSQLCommand);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDataTableAsync(RemoteService.ArrayOfXElement dsChangeDataSet, string strTableName)
        {
            return base.Channel.UpdateDataTableAsync(dsChangeDataSet, strTableName);
        }
        
        public System.Threading.Tasks.Task<RemoteService.ArrayOfXElement> GetSelectRuseltAsync(string strSelectCommand)
        {
            return base.Channel.GetSelectRuseltAsync(strSelectCommand);
        }
        
        public System.Threading.Tasks.Task<RemoteService.GetSelectResultResponse> GetSelectResultAsync(RemoteService.GetSelectResultRequest request)
        {
            return base.Channel.GetSelectResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<RemoteService.ArrayOfXElement> GetSystemParameterAsync(string strType)
        {
            return base.Channel.GetSystemParameterAsync(strType);
        }
        
        public System.Threading.Tasks.Task<string> GetDatabaseAsync()
        {
            return base.Channel.GetDatabaseAsync();
        }
        
        public System.Threading.Tasks.Task<string> CommSecurityStringAsync()
        {
            return base.Channel.CommSecurityStringAsync();
        }
        
        public System.Threading.Tasks.Task<int> ChangePassWordAsync(string sServer, string sDomain, string sUser, string sOldPass, string sNewPass)
        {
            return base.Channel.ChangePassWordAsync(sServer, sDomain, sUser, sOldPass, sNewPass);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.topmix.net/dataservice/GetData.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.topmix.net/dataservice/GetData.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "8.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
